"""Post-fix schematic files generated by kicad-mcp-pro sch_build_circuit (v4.1.0).

Works around three generator issues:
  1. Child-sheet symbol instances get a random root path and an empty project name,
     instead of /<root uuid>/<sheet uuid> and the project name.
  2. Power symbols are numbered #PWR001... on every sheet -> duplicates across sheets.
  3. Multi-unit symbols must be built under temporary per-unit references
     (the builder keys pin positions by reference only); rename them back here.
"""
import re, sys, pathlib

proj = pathlib.Path(sys.argv[1])
name = 'dual_adc_usb'
root = (proj / f'{name}.kicad_sch').read_text()
root_uuid = re.search(r'^\t\(uuid "([^"]+)"\)', root, re.M).group(1)
sheets = re.findall(r'\(sheet\b.*?\(uuid "([^"]+)"\).*?\(property "Sheetfile" "([^"]+)"', root, re.S)
RENAME = {f'U5U{u}': 'U501' for u in range(1, 6)}

for idx, (sheet_uuid, fname) in enumerate(sheets, start=1):
    f = proj / fname
    t = f.read_text()
    t = re.sub(r'\(project "[^"]*"\n(\s*)\(path "[^"]*"',
               lambda m: f'(project "{name}"\n{m.group(1)}(path "/{root_uuid}/{sheet_uuid}"', t)
    pwr = sorted(set(re.findall(r'#PWR\d+', t)), key=lambda s: int(s[4:]))
    mapping = {old: f'#PWR{idx}{n:03d}' for n, old in enumerate(pwr, start=1)}
    mapping.update(RENAME)
    t = re.sub(r'(\(property "Reference" "|\(reference ")([^"]+)"',
               lambda m: m.group(1) + mapping.get(m.group(2), m.group(2)) + '"', t)
    f.write_text(t)
    print(f'{fname}: path /{root_uuid}/{sheet_uuid}, {len(pwr)} power refs renumbered')
