"""ADC pair — 2× AD9235BCPZ-40, references, VCM divider, DRVDD ferrite
Block from: architecture/block_diagram.md  (block_id: adc_pair)
Interface nets: CH1_ADC_P/N, CH2_ADC_P/N, CLK_ADC1, CLK_ADC2, ADC1_D[11:0],
                ADC2_D[11:0], +3V0A, +3V3, VCM, GND

Implements architecture/net_plan.md "## ADC nets".

Both converters are clocked from the same 10 MHz source through matched buffer
outputs (see clock_gen), so the two channels sample simultaneously — SPEC F1.

Mode straps (handoffs/04_datasheets.md, AD9235 32-LFCSP):
    SENSE -> AGND   internal 1.0 V reference, 2 Vpp full-scale span
    MODE  -> AGND   offset binary, duty-cycle stabiliser off
    PDWN  -> AGND   converter always powered
The 32-lead LFCSP has NO OEB pin — net_plan.md lists an `OEB->GND` strap that does
not exist on this package (it belongs to the 28-lead TSSOP sibling). Pins 1, 3, 5
and 6 are DNC and are left truly unconnected per the datasheet.

*** ARCHITECTURE AMENDMENT A2 (architecture/driver_amendments.md) ***
OTR (out-of-range) is NOT routed to the FPGA. The GW1NR-9 QN88P has only 48 usable
3.3 V I/O and the design needs 47; net_plan.md pre-authorised dropping OTR ("droppable
— see R1"). Overrange stays detectable in firmware: in offset binary, a code of 0x000
or 0xFFF is the clipping indication that OTR duplicates.
"""
from skidl import *


@SubCircuit
def adc_pair(ch1_p, ch1_n, ch2_p, ch2_n, clk_adc1, clk_adc2, adc1_d, adc2_d,
             adc1_otr, adc2_otr, avdd, v3v3, vcm, gnd):
    """Two simultaneously-sampled 12-bit 10 MSPS converters.

    Args:
        ch1_p/ch1_n (Net): INPUT. Differential drive from analog_frontend CH1.
        ch2_p/ch2_n (Net): INPUT. Differential drive from analog_frontend CH2.
        clk_adc1/clk_adc2 (Net): INPUT. Phase-matched 10 MHz sample clocks.
        adc1_d/adc2_d (Bus): OUTPUT, 12 bits each, [0] = LSB. Offset binary.
        adc1_otr/adc2_otr (Net): Accepted for signature compatibility with the
                          architecture's block manifest but LEFT UNCONNECTED at the
                          ADC end per amendment A2. __main__.py does not route them.
        avdd (Net): INPUT. +3V0A analog supply (U6 LP5907-3.0).
        v3v3 (Net): INPUT. +3V3 digital rail; feeds DRVDD through FB4.
        vcm  (Net): OUTPUT of this block. 1.50 V common-mode reference generated by
                    the R28/R29 divider here and consumed by both analog_frontend
                    instances' VOCM pins.
        gnd  (Net): INPUT. Single GND net.

    Decoupling follows the datasheet: DRVDD (pin 16) gets its own 0.1 µF + 10 µF,
    separate from AVDD, and is fed through ferrite FB4 off +3V3 so the digital
    output drivers cannot pump the analog rail.
    """

    r_0402 = Part('Device', 'R', dest=TEMPLATE,
                  footprint='Resistor_SMD:R_0402_1005Metric')
    c_0402 = Part('Device', 'C', dest=TEMPLATE,
                  footprint='Capacitor_SMD:C_0402_1005Metric')
    c_0603 = Part('Device', 'C', dest=TEMPLATE,
                  footprint='Capacitor_SMD:C_0603_1608Metric')

    # ---- U9 / U10: AD9235BCPZ-40, 12-bit 40 MSPS (run at 10 MSPS) ----------------
    # Footprint corrected per handoffs/04_datasheets.md: the AD9235 CP-32 exposed pad
    # is 3.10x3.10mm, so the ADI LFCSP land pattern is used rather than the sourced
    # generic QFN-32 with a 3.45mm EP (see architecture/driver_amendments.md A4).
    adc = Part('dual_adc_usb', 'AD9235BCPZ-40', dest=TEMPLATE, value='AD9235BCPZ-40',
               footprint='Package_CSP:LFCSP-32-1EP_5x5mm_P0.5mm_EP3.1x3.1mm')
    U9 = adc(ref='U9')
    U10 = adc(ref='U10')

    # ---- FB4: DRVDD supply isolation off +3V3 ------------------------------------
    FB4 = Part('Device', 'FerriteBead', ref='FB4', value='600R@100MHz',
               footprint='Inductor_SMD:L_0603_1608Metric')
    v3v3_drv = Net('+3V3_DRV')
    # The ferrite passes power but is not a driver, so ERC would report every DRVDD
    # pin as under-driven. Declaring the downstream side POWER states the intent.
    v3v3_drv.drive = POWER
    v3v3 += FB4[1]
    v3v3_drv += FB4[2]

    # ---- VCM divider: 1.50 V from +3V0A (net_plan.md "VCM") ----------------------
    R28 = r_0402(ref='R28', value='10k')
    R29 = r_0402(ref='R29', value='10k')
    C58 = c_0603(ref='C58', value='1uF')
    C59 = c_0402(ref='C59', value='100nF')
    avdd & R28 & vcm & R29 & gnd
    vcm & C58 & gnd
    vcm & C59 & gnd

    # ---- Per-converter wiring ----------------------------------------------------
    caps = iter(range(48, 58))          # C48..C57 for the reference/decoupling network
    def wire(U, vin_p, vin_n, clk, dbus, n):
        """Wire one converter. `n` is 1 or 2, used only for net names."""
        # Analog inputs and clock
        U['VINP'] += vin_p
        U['VINN'] += vin_n
        U['CLK'] += clk

        # Mode straps — all to ground (see module docstring)
        U['SENSE'] += gnd
        U['MODE'] += gnd
        U['PDWN'] += gnd

        # DNC pins: the datasheet says do not connect. Mark them explicitly so ERC
        # does not report them as floating.
        for dnc in ('DNC', 'DNC2', 'DNC3', 'DNC4'):
            U[dnc] += NC

        # Reference network: VREF, REFT, REFB each decoupled, plus 10 µF across the
        # REFT/REFB pair (net_plan.md "ADC_REFT/ADC_REFB")
        vref = Net(f'ADC{n}_VREF')
        reft = Net(f'ADC_REFT{n}')
        refb = Net(f'ADC_REFB{n}')
        U['VREF'] += vref
        U['REFT'] += reft
        U['REFB'] += refb
        c_vref = c_0402(ref=f'C{next(caps)}', value='100nF')
        c_reft = c_0402(ref=f'C{next(caps)}', value='100nF')
        c_refb = c_0402(ref=f'C{next(caps)}', value='100nF')
        c_rdiff = c_0603(ref=f'C{next(caps)}', value='10uF')
        vref & c_vref & gnd
        reft & c_reft & gnd
        refb & c_refb & gnd
        reft & c_rdiff & refb

        # Supplies: AVDD (both pins) on +3V0A, DRVDD on the ferrite-isolated rail
        U['AVDD'] += avdd
        U['AVDD2'] += avdd
        U['AGND'] += gnd
        U['AGND2'] += gnd
        U['DGND'] += gnd
        U['DRVDD'] += v3v3_drv

        # Exposed pad: AD9235 CP-32 EP is the analog ground reference, pad 33.
        U['EP'] += gnd

        # Data outputs, [0] = LSB
        for i in range(12):
            U[f'D{i}'] += dbus[i]

        # OTR deliberately not routed — amendment A2.
        U['OTR'] += NC

    wire(U9, ch1_p, ch1_n, clk_adc1, adc1_d, 1)
    wire(U10, ch2_p, ch2_n, clk_adc2, adc2_d, 2)

    # ---- Decoupling: 100 nF + 10 µF per supply pin, per converter -----------------
    for ref_n, (U, rail) in enumerate(
            [(U9, avdd), (U10, avdd), (U9, v3v3_drv), (U10, v3v3_drv)], start=60):
        rail & c_0402(ref=f'C{ref_n}', value='100nF') & gnd
    for ref_n, rail in enumerate([avdd, v3v3_drv], start=64):
        rail & c_0603(ref=f'C{ref_n}', value='10uF') & gnd

    # ---- Test points (SPEC N5) ---------------------------------------------------
    tp = Part('Connector', 'TestPoint', dest=TEMPLATE,
              footprint='TestPoint:TestPoint_Pad_D1.0mm')
    for ref, net in [('TP10', avdd), ('TP11', v3v3_drv), ('TP12', vcm), ('TP13', gnd)]:
        tp(ref=ref, value=net.name)[1] += net
