"""Generate an iCE40 .pcf pin-constraint file from the schematic netlist (FPGA = ICE40HX4K-TQ144).
usage: python3 gen_pcf.py kicad/dual_adc_usb.net gateware/dual_adc_usb.pcf"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_pcb_netlist import parse_netlist  # noqa: E402

comps, nets = parse_netlist(sys.argv[1])
fpga = [r for r, c in comps.items() if c["value"].startswith("ICE40")][0]
SKIP = re.compile(r"^(GND|\+|-|VCCPLL|GNDPLL|unconnected|CFG_CDONE|CFG_CRESET)|/VCCPLL|/GNDPLL")
rows = []
for name, nodes in nets.items():
    for ref, pin in nodes:
        if ref == fpga and not SKIP.search(name):
            sig = name.split("/")[-1]
            m = re.match(r"^(DA|DB|SD_DQ|SD_A|SD_BA|FT_D|FT_ACBUS|GPIO)(\d+)$", sig)
            sig = f"{m.group(1).lower()}[{m.group(2)}]" if m else sig.lower()
            rows.append((sig, int(pin)))
os.makedirs(os.path.dirname(sys.argv[2]), exist_ok=True)
with open(sys.argv[2], "w") as f:
    f.write("# iCE40HX4K-TQ144 pin constraints for dual_adc_usb (generated by scripts/gen_pcf.py\n")
    f.write("# from kicad/dual_adc_usb.net; do not edit by hand -- FPGA pins follow the PCB).\n")
    def key(row):
        m = re.match(r"^(.*)\[(\d+)\]$", row[0])
        return (m.group(1), int(m.group(2))) if m else (row[0], -1)

    for sig, pin in sorted(rows, key=key):
        f.write(f"set_io {sig} {pin}\n")
print(len(rows), "signals ->", sys.argv[2])
