from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

skidl_REPL = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'USB_C_Receptacle_USB2.0_16P', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'USB_C_Receptacle_USB2.0_16P'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_USB:USB_C_Receptacle_HRO_TYPE-C-31-M-12', 'keywords':'usb universal serial bus type-C USB2.0', 'description':'USB 2.0-only 16P Type-C Receptacle connector', 'datasheet':'https://www.usb.org/sites/default/files/documents/usb_type-c.zip', 'pins':[
            Pin(num='S1',name='SHIELD',func=pin_types.PASSIVE,unit=1),
            Pin(num='A1',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='A12',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='B1',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='B12',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='A4',name='VBUS',func=pin_types.PASSIVE,unit=1),
            Pin(num='A9',name='VBUS',func=pin_types.PASSIVE,unit=1),
            Pin(num='B4',name='VBUS',func=pin_types.PASSIVE,unit=1),
            Pin(num='B9',name='VBUS',func=pin_types.PASSIVE,unit=1),
            Pin(num='A5',name='CC1',func=pin_types.BIDIR,unit=1),
            Pin(num='B5',name='CC2',func=pin_types.BIDIR,unit=1),
            Pin(num='A7',name='D-',func=pin_types.BIDIR,unit=1),
            Pin(num='B7',name='D-',func=pin_types.BIDIR,unit=1),
            Pin(num='A6',name='D+',func=pin_types.BIDIR,unit=1),
            Pin(num='B6',name='D+',func=pin_types.BIDIR,unit=1),
            Pin(num='A8',name='SBU1',func=pin_types.BIDIR,unit=1),
            Pin(num='B8',name='SBU2',func=pin_types.BIDIR,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R'}), 'ref_prefix':'R', 'fplist':[''], 'footprint':'Resistor_SMD:R_0402_1005Metric', 'keywords':'R res resistor', 'description':'Resistor', 'datasheet':'~', 'pins':[
            Pin(num='1',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='~',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Polyfuse', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Polyfuse'}), 'ref_prefix':'F', 'fplist':[''], 'footprint':'Fuse:Fuse_1206_3216Metric', 'keywords':'resettable fuse PTC PPTC polyfuse polyswitch', 'description':'Resettable fuse, polymeric positive temperature coefficient', 'datasheet':'~', 'pins':[
            Pin(num='1',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='~',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'SMF5V0A', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SMF5V0A'}), 'ref_prefix':'D', 'fplist':['Diode_SMD:D_SMB', 'Diode_SMD:D_SMF'], 'footprint':'Diode_SMD:D_SOD-123F', 'keywords':'diode TVS voltage suppressor', 'description':'200W unidirectional Transil Transient Voltage Suppressor, 5Vrwm, SMF', 'datasheet':'https://www.vishay.com/doc?85881', 'pins':[
            Pin(num='1',name='A1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='A2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'USBLC6-2SC6', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'USBLC6-2SC6'}), 'ref_prefix':'U', 'fplist':['Package_TO_SOT_SMD:SOT-666', 'Package_TO_SOT_SMD:SOT-23-6'], 'footprint':'Package_TO_SOT_SMD:SOT-23-6', 'keywords':'usb ethernet video', 'description':'Very low capacitance ESD protection diode, 2 data-line, SOT-23-6', 'datasheet':'https://www.st.com/resource/en/datasheet/usblc6-2.pdf', 'pins':[
            Pin(num='1',name='I/O1',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='I/O2',func=pin_types.PASSIVE,unit=1),
            Pin(num='5',name='VBUS',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='6',name='I/O1',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='I/O2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'C', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C'}), 'ref_prefix':'C', 'fplist':[''], 'footprint':'Capacitor_SMD:C_0603_1608Metric', 'keywords':'cap capacitor', 'description':'Unpolarized capacitor', 'datasheet':'~', 'pins':[
            Pin(num='1',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='~',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'TPS22918DBVR', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TPS22918DBVR'}), 'ref_prefix':'U', 'fplist':[''], 'footprint':'Package_TO_SOT_SMD:SOT-23-6', 'keywords':'', 'description':'', 'datasheet':'', 'pins':[
            Pin(num='1',name='VIN',func=pin_types.PWRIN,unit=1),
            Pin(num='3',name='ON',func=pin_types.INPUT,unit=1),
            Pin(num='5',name='QOD',func=pin_types.PASSIVE,unit=1),
            Pin(num='6',name='VOUT',func=pin_types.PWROUT,unit=1),
            Pin(num='2',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='4',name='CT',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'TLV62569DBV', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TLV62569DBV'}), 'ref_prefix':'U', 'fplist':['Package_TO_SOT_SMD:SOT-23-5', 'Package_TO_SOT_SMD:SOT-23-5'], 'footprint':'Package_TO_SOT_SMD:SOT-23-5', 'keywords':'Step-Down Buck DC-DC Regulator Adjustable', 'description':'High Efficiency Synchronous Buck Converter, Adjustable Output 0.6V-5.5V, 2A, SOT-23-5', 'datasheet':'http://www.ti.com/lit/ds/symlink/tlv62569.pdf', 'pins':[
            Pin(num='4',name='VIN',func=pin_types.PWRIN,unit=1),
            Pin(num='1',name='EN',func=pin_types.INPUT,unit=1),
            Pin(num='2',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='3',name='SW',func=pin_types.PWROUT,unit=1),
            Pin(num='5',name='FB',func=pin_types.INPUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'L', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'L'}), 'ref_prefix':'L', 'fplist':[''], 'footprint':'Inductor_SMD:L_Changjiang_FNR4020S', 'keywords':'inductor choke coil reactor magnetic', 'description':'Inductor', 'datasheet':'~', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'TLV75733PDBV', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TLV75733PDBV'}), 'ref_prefix':'U', 'fplist':['Package_TO_SOT_SMD:SOT-23-5', 'Package_TO_SOT_SMD:SOT-23-5'], 'footprint':'Package_TO_SOT_SMD:SOT-23-5', 'keywords':'LDO Regulator Fixed Positive', 'description':'1A Low IQ Small Size Low Dropout Voltage Regulator, Fixed Output 3.3V, SOT-23-5', 'datasheet':'https://www.ti.com/lit/ds/symlink/tlv757p.pdf', 'pins':[
            Pin(num='1',name='IN',func=pin_types.PWRIN,unit=1),
            Pin(num='3',name='EN',func=pin_types.INPUT,unit=1),
            Pin(num='2',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='4',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='5',name='OUT',func=pin_types.PWROUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'LM27762', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LM27762'}), 'ref_prefix':'U', 'fplist':['Package_SON:WSON-12-1EP_3x2mm_P0.5mm_EP1x2.65_ThermalVias'], 'footprint':'Package_SON:WSON-12-1EP_3x2mm_P0.5mm_EP1x2.65', 'keywords':"Low-noise inverting charge pump with both positive and negative LDO's", 'description':"Low-noise inverting charge pump with both positive and negative LDO's, with 2.7V-5.5V input to +1.5 to +5V and -1.5 to -5V Output Voltage, WSON-12", 'datasheet':'http://www.ti.com/lit/ds/symlink/lm27762.pdf', 'pins':[
            Pin(num='3',name='VIN',func=pin_types.PWRIN,unit=1),
            Pin(num='1',name='PGOOD',func=pin_types.OPENCOLL,unit=1),
            Pin(num='8',name='EN-',func=pin_types.INPUT,unit=1),
            Pin(num='12',name='EN+',func=pin_types.INPUT,unit=1),
            Pin(num='10',name='C+',func=pin_types.PASSIVE,unit=1),
            Pin(num='9',name='C-',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='13',name='PAD',func=pin_types.PWRIN,unit=1),
            Pin(num='11',name='OUT+',func=pin_types.PWROUT,unit=1),
            Pin(num='2',name='FB+',func=pin_types.INPUT,unit=1),
            Pin(num='7',name='FB-',func=pin_types.INPUT,unit=1),
            Pin(num='6',name='OUT-',func=pin_types.PWROUT,unit=1),
            Pin(num='5',name='CP',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_Coaxial', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_Coaxial'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'ProjectLocal:KH-BNC50-3511', 'keywords':'BNC SMA SMB SMC LEMO coaxial connector CINCH RCA MCX MMCX U.FL UMRF', 'description':'coaxial connector (BNC, SMA, SMB, SMC, Cinch/RCA, LEMO, ...)', 'datasheet':'~', 'pins':[
            Pin(num='1',name='In',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Ext',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'C_Trim', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C_Trim'}), 'ref_prefix':'C', 'fplist':[''], 'footprint':'Capacitor_SMD:C_Trimmer_Voltronics_JZ', 'keywords':'trimmer variable capacitor', 'description':'Trimmable capacitor', 'datasheet':'~', 'pins':[
            Pin(num='1',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='~',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'BAV99', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'BAV99'}), 'ref_prefix':'D', 'fplist':['Package_TO_SOT_SMD:SOT-23'], 'footprint':'Package_TO_SOT_SMD:SOT-23', 'keywords':'diode', 'description':'BAV99 High-speed switching diodes, SOT-23', 'datasheet':'https://assets.nexperia.com/documents/data-sheet/BAV99_SER.pdf', 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='K',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='A',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'OPA810xDBV', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'OPA810xDBV'}), 'ref_prefix':'U', 'fplist':['Package_TO_SOT_SMD:SOT-23-5', 'Package_TO_SOT_SMD:SOT-23-5'], 'footprint':'Package_TO_SOT_SMD:SOT-23-5', 'keywords':'single opamp', 'description':'140-MHz, Rail-to-Rail Input and Output, FET-Input Operational Amplifier, SOT-23-5', 'datasheet':'https://www.ti.com/lit/ds/symlink/opa810.pdf', 'pins':[
            Pin(num='5',name='V+',func=pin_types.PWRIN),
            Pin(num='2',name='V-',func=pin_types.PWRIN),
            Pin(num='3',name='+',func=pin_types.INPUT,unit=1),
            Pin(num='4',name='-',func=pin_types.INPUT,unit=1),
            Pin(num='1',name='~',func=pin_types.OUTPUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'THS4521IDGK', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'THS4521IDGK'}), 'ref_prefix':'U', 'fplist':['Package_SO:VSSOP-8_3x3mm_P0.65mm'], 'footprint':'Package_SO:MSOP-8_3x3mm_P0.65mm', 'keywords':'differential amplifier', 'description':'Very Low Power, Negative Rail Input, Rail to Rail Output, Fully Differential Amplifier, VSSOP-8', 'datasheet':'https://www.ti.com/lit/ds/symlink/ths4521.pdf', 'pins':[
            Pin(num='8',name='+',func=pin_types.INPUT,unit=1),
            Pin(num='7',name='~{PD}',func=pin_types.INPUT,unit=1),
            Pin(num='2',name='V_{OCM}',func=pin_types.INPUT,unit=1),
            Pin(num='1',name='-',func=pin_types.INPUT,unit=1),
            Pin(num='3',name='V_{S+}',func=pin_types.PWRIN,unit=1),
            Pin(num='6',name='V_{S-}',func=pin_types.PWRIN,unit=1),
            Pin(num='5',func=pin_types.OUTPUT,unit=1),
            Pin(num='4',func=pin_types.OUTPUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'ADS5231IPAGT', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'ADS5231IPAGT'}), 'ref_prefix':'U', 'fplist':[''], 'footprint':'Package_QFP:TQFP-64_10x10mm_P0.5mm', 'keywords':'', 'description':'', 'datasheet':'', 'pins':[
            Pin(num='1',name='SEL',func=pin_types.INPUT,unit=1),
            Pin(num='6',name='OEB',func=pin_types.INPUT,unit=1),
            Pin(num='24',name='CLK',func=pin_types.INPUT,unit=1),
            Pin(num='41',name='MSBI/SEN',func=pin_types.INPUT,unit=1),
            Pin(num='42',name='OEA/SCLK',func=pin_types.INPUT,unit=1),
            Pin(num='45',name='STPD/SDATA',func=pin_types.INPUT,unit=1),
            Pin(num='50',name='INA',func=pin_types.INPUT,unit=1),
            Pin(num='51',name='~{INA}',func=pin_types.INPUT,unit=1),
            Pin(num='52',name='CM',func=pin_types.OUTPUT,unit=1),
            Pin(num='53',name='REFT',func=pin_types.PASSIVE,unit=1),
            Pin(num='54',name='REFB',func=pin_types.PASSIVE,unit=1),
            Pin(num='56',name='INT/~{EXT}',func=pin_types.INPUT,unit=1),
            Pin(num='60',name='ISET',func=pin_types.PASSIVE,unit=1),
            Pin(num='62',name='~{INB}',func=pin_types.INPUT,unit=1),
            Pin(num='63',name='INB',func=pin_types.INPUT,unit=1),
            Pin(num='9',name='OVRB',func=pin_types.OUTPUT,unit=1),
            Pin(num='10',name='D0_B',func=pin_types.OUTPUT,unit=1),
            Pin(num='11',name='D1_B',func=pin_types.OUTPUT,unit=1),
            Pin(num='12',name='D2_B',func=pin_types.OUTPUT,unit=1),
            Pin(num='13',name='D3_B',func=pin_types.OUTPUT,unit=1),
            Pin(num='14',name='D4_B',func=pin_types.OUTPUT,unit=1),
            Pin(num='15',name='D5_B',func=pin_types.OUTPUT,unit=1),
            Pin(num='16',name='D6_B',func=pin_types.OUTPUT,unit=1),
            Pin(num='17',name='D7_B',func=pin_types.OUTPUT,unit=1),
            Pin(num='18',name='D8_B',func=pin_types.OUTPUT,unit=1),
            Pin(num='19',name='D9_B',func=pin_types.OUTPUT,unit=1),
            Pin(num='20',name='D10_B',func=pin_types.OUTPUT,unit=1),
            Pin(num='21',name='D11_B',func=pin_types.OUTPUT,unit=1),
            Pin(num='22',name='DVB',func=pin_types.OUTPUT,unit=1),
            Pin(num='26',name='DVA',func=pin_types.OUTPUT,unit=1),
            Pin(num='27',name='D0_A',func=pin_types.OUTPUT,unit=1),
            Pin(num='28',name='D1_A',func=pin_types.OUTPUT,unit=1),
            Pin(num='29',name='D2_A',func=pin_types.OUTPUT,unit=1),
            Pin(num='30',name='D3_A',func=pin_types.OUTPUT,unit=1),
            Pin(num='31',name='D4_A',func=pin_types.OUTPUT,unit=1),
            Pin(num='32',name='D5_A',func=pin_types.OUTPUT,unit=1),
            Pin(num='33',name='D6_A',func=pin_types.OUTPUT,unit=1),
            Pin(num='34',name='D7_A',func=pin_types.OUTPUT,unit=1),
            Pin(num='35',name='D8_A',func=pin_types.OUTPUT,unit=1),
            Pin(num='36',name='D9_A',func=pin_types.OUTPUT,unit=1),
            Pin(num='37',name='D10_A',func=pin_types.OUTPUT,unit=1),
            Pin(num='38',name='D11_A',func=pin_types.OUTPUT,unit=1),
            Pin(num='39',name='OVRA',func=pin_types.OUTPUT,unit=1),
            Pin(num='3',name='AVDD',func=pin_types.PWRIN,unit=1),
            Pin(num='5',name='VDRV',func=pin_types.PWRIN,unit=1),
            Pin(num='8',name='VDRV',func=pin_types.PWRIN,unit=1),
            Pin(num='40',name='VDRV',func=pin_types.PWRIN,unit=1),
            Pin(num='43',name='VDRV',func=pin_types.PWRIN,unit=1),
            Pin(num='46',name='AVDD',func=pin_types.PWRIN,unit=1),
            Pin(num='57',name='AVDD',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='AGND',func=pin_types.PWRIN,unit=1),
            Pin(num='4',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='7',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='23',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='25',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='44',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='47',name='AGND',func=pin_types.PWRIN,unit=1),
            Pin(num='48',name='AGND',func=pin_types.PWRIN,unit=1),
            Pin(num='49',name='AGND',func=pin_types.PWRIN,unit=1),
            Pin(num='55',name='AGND',func=pin_types.PWRIN,unit=1),
            Pin(num='58',name='AGND',func=pin_types.PWRIN,unit=1),
            Pin(num='59',name='AGND',func=pin_types.PWRIN,unit=1),
            Pin(num='61',name='AGND',func=pin_types.PWRIN,unit=1),
            Pin(num='64',name='AGND',func=pin_types.PWRIN,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'ASE-xxxMHz', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'ASE-xxxMHz'}), 'ref_prefix':'Y', 'fplist':['Oscillator:Oscillator_SMD_Abracon_ASE-4Pin_3.2x2.5mm'], 'footprint':'Oscillator:Oscillator_SMD_Abracon_ASE-4Pin_3.2x2.5mm', 'keywords':'3.3V CMOS SMD Crystal Clock Oscillator', 'description':'3.3V CMOS SMD Crystal Clock Oscillator, Abracon', 'datasheet':'http://www.abracon.com/Oscillators/ASV.pdf', 'pins':[
            Pin(num='1',name='EN',func=pin_types.INPUT,unit=1),
            Pin(num='4',name='Vdd',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='3',name='OUT',func=pin_types.OUTPUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'74LVC1G34', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'74LVC1G34'}), 'ref_prefix':'U', 'fplist':[''], 'footprint':'Package_TO_SOT_SMD:SOT-353_SC-70-5', 'keywords':'Single Gate Buff LVC CMOS', 'description':'Single Buffer Gate, Low-Voltage CMOS', 'datasheet':'https://www.ti.com/lit/ds/symlink/sn74lvc1g34.pdf', 'pins':[
            Pin(num='2',name='~',func=pin_types.INPUT,unit=1),
            Pin(num='5',name='VCC',func=pin_types.PWRIN,unit=1),
            Pin(num='3',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='1',name='NC',func=pin_types.FREE,unit=1),
            Pin(num='4',name='~',func=pin_types.OUTPUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'GW1NR-LV9QN88PC6', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'GW1NR-LV9QN88PC6'}), 'ref_prefix':'U', 'fplist':[''], 'footprint':'Package_DFN_QFN:ArtInChip_QFN-88-1EP_10x10mm_P0.4mm_EP6.74x6.74mm', 'keywords':'', 'description':'', 'datasheet':'', 'pins':[
            Pin(num='3',name='IOT2A',func=pin_types.BIDIR,unit=1),
            Pin(num='4',name='IOL5A/JTAGSEL_N/LPLL_T_in',func=pin_types.BIDIR,unit=1),
            Pin(num='5',name='IOL11A/TMS',func=pin_types.BIDIR,unit=1),
            Pin(num='6',name='IOL11B/TCK',func=pin_types.BIDIR,unit=1),
            Pin(num='7',name='IOL12B/TDI',func=pin_types.BIDIR,unit=1),
            Pin(num='8',name='IOL13A/TDO',func=pin_types.BIDIR,unit=1),
            Pin(num='9',name='IOL13B/RECONFIG_N',func=pin_types.BIDIR,unit=1),
            Pin(num='10',name='IOL15A/GCLKT_6',func=pin_types.BIDIR,unit=1),
            Pin(num='11',name='IOL16B',func=pin_types.BIDIR,unit=1),
            Pin(num='13',name='IOL21B',func=pin_types.BIDIR,unit=1),
            Pin(num='14',name='IOL22B',func=pin_types.BIDIR,unit=1),
            Pin(num='15',name='IOL25B',func=pin_types.BIDIR,unit=1),
            Pin(num='16',name='IOL26B',func=pin_types.BIDIR,unit=1),
            Pin(num='79',name='IOT12B',func=pin_types.BIDIR,unit=1),
            Pin(num='80',name='IOT12A',func=pin_types.BIDIR,unit=1),
            Pin(num='81',name='IOT11B',func=pin_types.BIDIR,unit=1),
            Pin(num='82',name='IOT11A',func=pin_types.BIDIR,unit=1),
            Pin(num='83',name='IOT10B',func=pin_types.BIDIR,unit=1),
            Pin(num='84',name='IOT10A',func=pin_types.BIDIR,unit=1),
            Pin(num='85',name='IOT8B',func=pin_types.BIDIR,unit=1),
            Pin(num='86',name='IOT8A',func=pin_types.BIDIR,unit=1),
            Pin(num='87',name='IOT6B/MODE1',func=pin_types.BIDIR,unit=1),
            Pin(num='88',name='IOT5A/MODE0',func=pin_types.BIDIR,unit=1),
            Pin(num='48',name='IOR24B',func=pin_types.BIDIR,unit=1),
            Pin(num='49',name='IOR24A',func=pin_types.BIDIR,unit=1),
            Pin(num='50',name='IOR22B',func=pin_types.BIDIR,unit=1),
            Pin(num='51',name='IOR17B/GCLKC_3',func=pin_types.BIDIR,unit=1),
            Pin(num='52',name='IOR17A/GCLKT_3',func=pin_types.BIDIR,unit=1),
            Pin(num='53',name='IOR15B/DOUT/WE_N',func=pin_types.BIDIR,unit=1),
            Pin(num='54',name='IOR15A/DIN/CLKHOLD_N',func=pin_types.BIDIR,unit=1),
            Pin(num='55',name='IOR14B/SSPI_CS_N/D0',func=pin_types.BIDIR,unit=1),
            Pin(num='56',name='IOR14A/SO/D1',func=pin_types.BIDIR,unit=1),
            Pin(num='57',name='IOR13A/FASTRD_N/D3',func=pin_types.BIDIR,unit=1),
            Pin(num='59',name='IOR12B/MCLK/D4',func=pin_types.BIDIR,unit=1),
            Pin(num='60',name='IOR12A/MCS_N/D5',func=pin_types.BIDIR,unit=1),
            Pin(num='61',name='IOR11B/MO/D6',func=pin_types.BIDIR,unit=1),
            Pin(num='62',name='IOR11A/MI/D7',func=pin_types.BIDIR,unit=1),
            Pin(num='63',name='IOR5A/RPLL_T_in',func=pin_types.BIDIR,unit=1),
            Pin(num='68',name='IOT42B',func=pin_types.BIDIR,unit=1),
            Pin(num='69',name='IOT42A',func=pin_types.BIDIR,unit=1),
            Pin(num='70',name='IOT41B',func=pin_types.BIDIR,unit=1),
            Pin(num='71',name='IOT41A',func=pin_types.BIDIR,unit=1),
            Pin(num='72',name='IOT39B',func=pin_types.BIDIR,unit=1),
            Pin(num='73',name='IOT39A',func=pin_types.BIDIR,unit=1),
            Pin(num='74',name='IOT38B',func=pin_types.BIDIR,unit=1),
            Pin(num='75',name='IOT38A',func=pin_types.BIDIR,unit=1),
            Pin(num='76',name='IOT37B',func=pin_types.BIDIR,unit=1),
            Pin(num='77',name='IOT37A',func=pin_types.BIDIR,unit=1),
            Pin(num='1',name='VCC',func=pin_types.PWRIN,unit=1),
            Pin(num='12',name='VCCO3',func=pin_types.PWRIN,unit=1),
            Pin(num='22',name='VCC',func=pin_types.PWRIN,unit=1),
            Pin(num='23',name='VCCO2',func=pin_types.PWRIN,unit=1),
            Pin(num='44',name='VCCO2',func=pin_types.PWRIN,unit=1),
            Pin(num='45',name='VCC',func=pin_types.PWRIN,unit=1),
            Pin(num='58',name='VCCO1',func=pin_types.PWRIN,unit=1),
            Pin(num='64',name='VCCX/VCCO0',func=pin_types.PWRIN,unit=1),
            Pin(num='66',name='VCC',func=pin_types.PWRIN,unit=1),
            Pin(num='67',name='VCCX/VCCO0',func=pin_types.PWRIN,unit=1),
            Pin(num='78',name='VCCX/VCCO0',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='VSS',func=pin_types.PWRIN,unit=1),
            Pin(num='17',name='IOB2A',func=pin_types.BIDIR,unit=1),
            Pin(num='18',name='IOB2B',func=pin_types.BIDIR,unit=1),
            Pin(num='19',name='IOB4A',func=pin_types.BIDIR,unit=1),
            Pin(num='20',name='IOB4B',func=pin_types.BIDIR,unit=1),
            Pin(num='21',name='VSS',func=pin_types.PWRIN,unit=1),
            Pin(num='24',name='VSS',func=pin_types.PWRIN,unit=1),
            Pin(num='25',name='IOB8A',func=pin_types.BIDIR,unit=1),
            Pin(num='26',name='IOB8B',func=pin_types.BIDIR,unit=1),
            Pin(num='27',name='IOB11A',func=pin_types.BIDIR,unit=1),
            Pin(num='28',name='IOB11B',func=pin_types.BIDIR,unit=1),
            Pin(num='29',name='IOB13A',func=pin_types.BIDIR,unit=1),
            Pin(num='30',name='IOB13B',func=pin_types.BIDIR,unit=1),
            Pin(num='31',name='IOB15A',func=pin_types.BIDIR,unit=1),
            Pin(num='32',name='IOB15B',func=pin_types.BIDIR,unit=1),
            Pin(num='33',name='IOB23A',func=pin_types.BIDIR,unit=1),
            Pin(num='34',name='IOB23B',func=pin_types.BIDIR,unit=1),
            Pin(num='35',name='IOB29A/GCLKT_4',func=pin_types.BIDIR,unit=1),
            Pin(num='36',name='IOB29B/GCLKC_4',func=pin_types.BIDIR,unit=1),
            Pin(num='37',name='IOB31A',func=pin_types.BIDIR,unit=1),
            Pin(num='38',name='IOB31B',func=pin_types.BIDIR,unit=1),
            Pin(num='39',name='IOB33A',func=pin_types.BIDIR,unit=1),
            Pin(num='40',name='IOB33B',func=pin_types.BIDIR,unit=1),
            Pin(num='41',name='IOB41A',func=pin_types.BIDIR,unit=1),
            Pin(num='42',name='IOB41B',func=pin_types.BIDIR,unit=1),
            Pin(num='43',name='VSS',func=pin_types.PWRIN,unit=1),
            Pin(num='46',name='VSS',func=pin_types.PWRIN,unit=1),
            Pin(num='47',name='IOB43B',func=pin_types.BIDIR,unit=1),
            Pin(num='65',name='VSS',func=pin_types.PWRIN,unit=1),
            Pin(num='89',name='EP',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'LED', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LED'}), 'ref_prefix':'D', 'fplist':[''], 'footprint':'LED_SMD:LED_0603_1608Metric', 'keywords':'LED diode', 'description':'Light emitting diode', 'datasheet':'~', 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='A',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_01x03', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x03'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_PinHeader_2.54mm:PinHeader_1x03_P2.54mm_Vertical', 'keywords':'connector', 'description':'Generic connector, single row, 01x03, script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'~', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='Pin_3',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_01x06', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x06'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_PinHeader_2.54mm:PinHeader_1x06_P2.54mm_Vertical', 'keywords':'connector', 'description':'Generic connector, single row, 01x06, script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'~', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='Pin_3',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='Pin_4',func=pin_types.PASSIVE,unit=1),
            Pin(num='5',name='Pin_5',func=pin_types.PASSIVE,unit=1),
            Pin(num='6',name='Pin_6',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'FT232H', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'FT232H'}), 'ref_prefix':'U', 'fplist':[''], 'footprint':'Package_QFP:LQFP-48_7x7mm_P0.5mm', 'keywords':'FTDI USB Single UART FIFO', 'description':'Hi Speed Single Channel USB UART/FIFO, LQFP/QFN-48', 'datasheet':'https://www.ftdichip.com/Support/Documents/DataSheets/ICs/DS_FT232H.pdf', 'pins':[
            Pin(num='40',name='VREGIN',func=pin_types.PWRIN,unit=1),
            Pin(num='39',name='VCCD',func=pin_types.PWROUT,unit=1),
            Pin(num='38',name='VCCCORE',func=pin_types.PWROUT,unit=1),
            Pin(num='37',name='VCCA',func=pin_types.PWRIN,unit=1),
            Pin(num='6',name='DM',func=pin_types.BIDIR,unit=1),
            Pin(num='7',name='DP',func=pin_types.BIDIR,unit=1),
            Pin(num='34',name='~{RESET}',func=pin_types.INPUT,unit=1),
            Pin(num='5',name='REF',func=pin_types.INPUT,unit=1),
            Pin(num='45',name='EECS',func=pin_types.OUTPUT,unit=1),
            Pin(num='44',name='EECLK',func=pin_types.OUTPUT,unit=1),
            Pin(num='43',name='EEDATA',func=pin_types.BIDIR,unit=1),
            Pin(num='1',name='XCSI',func=pin_types.INPUT,unit=1),
            Pin(num='2',name='XCSO',func=pin_types.OUTPUT,unit=1),
            Pin(num='42',name='TEST',func=pin_types.INPUT,unit=1),
            Pin(num='4',name='AGND',func=pin_types.PWRIN,unit=1),
            Pin(num='9',name='AGND',func=pin_types.PWRIN,unit=1),
            Pin(num='3',name='VPHY',func=pin_types.PWRIN,unit=1),
            Pin(num='41',name='AGND',func=pin_types.PWRIN,unit=1),
            Pin(num='8',name='VPLL',func=pin_types.PWRIN,unit=1),
            Pin(num='10',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='12',name='VCCIO',func=pin_types.PWRIN,unit=1),
            Pin(num='11',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='24',name='VCCIO',func=pin_types.PWRIN,unit=1),
            Pin(num='22',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='46',name='VCCIO',func=pin_types.PWRIN,unit=1),
            Pin(num='23',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='35',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='36',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='47',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='48',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='13',name='ADBUS0',func=pin_types.BIDIR,unit=1),
            Pin(num='14',name='ADBUS1',func=pin_types.BIDIR,unit=1),
            Pin(num='15',name='ADBUS2',func=pin_types.BIDIR,unit=1),
            Pin(num='16',name='ADBUS3',func=pin_types.BIDIR,unit=1),
            Pin(num='17',name='ADBUS4',func=pin_types.BIDIR,unit=1),
            Pin(num='18',name='ADBUS5',func=pin_types.BIDIR,unit=1),
            Pin(num='19',name='ADBUS6',func=pin_types.BIDIR,unit=1),
            Pin(num='20',name='ADBUS7',func=pin_types.BIDIR,unit=1),
            Pin(num='21',name='ACBUS0',func=pin_types.BIDIR,unit=1),
            Pin(num='25',name='ACBUS1',func=pin_types.BIDIR,unit=1),
            Pin(num='26',name='ACBUS2',func=pin_types.BIDIR,unit=1),
            Pin(num='27',name='ACBUS3',func=pin_types.BIDIR,unit=1),
            Pin(num='28',name='ACBUS4',func=pin_types.BIDIR,unit=1),
            Pin(num='29',name='ACBUS5',func=pin_types.BIDIR,unit=1),
            Pin(num='30',name='ACBUS6',func=pin_types.BIDIR,unit=1),
            Pin(num='31',name='ACBUS7',func=pin_types.BIDIR,unit=1),
            Pin(num='32',name='ACBUS8',func=pin_types.BIDIR,unit=1),
            Pin(num='33',name='ACBUS9',func=pin_types.BIDIR,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'93LCxxBxxOT', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'93LCxxBxxOT'}), 'ref_prefix':'U', 'fplist':['Package_TO_SOT_SMD:SOT-23-6', 'Package_TO_SOT_SMD:SOT-23-6'], 'footprint':'Package_TO_SOT_SMD:SOT-23-6', 'keywords':'1K Microwire Serial EEPROM', 'description':'Serial EEPROM, 93 Series, 2.5V, SOT-23-6', 'datasheet':'http://ww1.microchip.com/downloads/en/DeviceDoc/20001749K.pdf', 'pins':[
            Pin(num='5',name='CS',func=pin_types.INPUT,unit=1),
            Pin(num='6',name='VCC',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='4',name='CLK',func=pin_types.INPUT,unit=1),
            Pin(num='3',name='DI',func=pin_types.INPUT,unit=1),
            Pin(num='1',name='DO',func=pin_types.TRISTATE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Crystal_GND24', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Crystal_GND24'}), 'ref_prefix':'Y', 'fplist':[''], 'footprint':'Crystal:Crystal_SMD_3225-4Pin_3.2x2.5mm', 'keywords':'quartz ceramic resonator oscillator', 'description':'Four pin crystal, GND on pins 2 and 4', 'datasheet':'~', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='G',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='G',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='3',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] })])