"""Dual-ADC USB Streaming Digitizer — assembled modular circuit.

Generated by skidl-assembler from the block manifest in handoffs/02_architecture.md and
the 9 completed block files in this package. Wires together:

    usb_c_input, power_digital, power_analog, clock_gen, afe_channel (x2),
    adc_channel (x2), sram_buffer, usb_bridge, fpga_core

Net names match architecture/net_plan.md verbatim. Run with:

    cd <project_root> && \
    KICAD9_SYMBOL_DIR=/usr/share/kicad/symbols \
    KICAD9_FOOTPRINT_DIR=/usr/share/kicad/footprints \
    python3 -m circuits.dual_adc_usb
"""
from skidl import *

# Import all block functions (final signatures per handoffs/05_blocks/*.md)
from .usb_c_input import usb_c_input
from .power_digital import power_digital
from .power_analog import power_analog
from .clock_gen import clock_gen
from .afe_channel import afe_channel
from .adc_channel import adc_channel
from .sram_buffer import sram_buffer
from .usb_bridge import usb_bridge
from .fpga_core import fpga_core

# ---------------------------------------------------------------------------
# Top-level nets (architecture/net_plan.md, sections 1-9)
# ---------------------------------------------------------------------------

# --- Power nets ---
VBUS = Net('VBUS')
GND = Net('GND')
V3V3_D = Net('V3V3_D')
V1V2 = Net('V1V2')
V5_A = Net('V5_A')
VN5_A = Net('VN5_A')
V3V3_A = Net('V3V3_A')
V3V3_CLK = Net('V3V3_CLK')
VREF_0V5_A = Net('VREF_0V5_A')
VREF_0V5_B = Net('VREF_0V5_B')
PWREN_N = Net('PWREN_N')

# VBUS and GND have no active regulator-output pin of their own (VBUS is fed from the
# J1 connector through a fuse; GND has no single "source" pin at all) — mark both POWER
# explicitly so ERC treats them as legitimately driven. All other power rails
# (V3V3_D/V1V2 by power_digital, V3V3_A/V3V3_CLK/V5_A/VN5_A/VREF_0V5_A/VREF_0V5_B by
# power_analog) already have `.drive = POWER` set inside their driving block, on the
# same Net objects passed in below — no need to repeat that here.
VBUS.drive = POWER
GND.drive = POWER

# --- USB nets ---
USB_DP = Net('USB_DP')
USB_DM = Net('USB_DM')

# --- Analog signal nets (per channel) ---
BNC_A_SIG = Net('BNC_A_SIG')
BNC_B_SIG = Net('BNC_B_SIG')
ADC_A_IN = Net('ADC_A_IN')
ADC_B_IN = Net('ADC_B_IN')
ADC_A_VINN = Net('ADC_A_VINN')
ADC_B_VINN = Net('ADC_B_VINN')

# --- Clock nets ---
CLK_ADC_A = Net('CLK_ADC_A')
CLK_ADC_B = Net('CLK_ADC_B')
CLK_10M = Net('CLK_10M')
CLK60 = Net('CLK60')

# --- ADC status/control nets ---
ADCA_OTR = Net('ADCA_OTR')
ADCA_PDWN = Net('ADCA_PDWN')
ADCB_OTR = Net('ADCB_OTR')
ADCB_PDWN = Net('ADCB_PDWN')

# --- SRAM control nets ---
SRAM_CE_N = Net('SRAM_CE_N')
SRAM_OE_N = Net('SRAM_OE_N')
SRAM_WE_N = Net('SRAM_WE_N')
SRAM_UB_N = Net('SRAM_UB_N')
SRAM_LB_N = Net('SRAM_LB_N')

# --- FT245 FIFO control nets ---
FIFO_RXF_N = Net('FIFO_RXF_N')
FIFO_TXE_N = Net('FIFO_TXE_N')
FIFO_RD_N = Net('FIFO_RD_N')
FIFO_WR_N = Net('FIFO_WR_N')
FIFO_OE_N = Net('FIFO_OE_N')

# --- FPGA housekeeping nets ---
EXT_TRIG = Net('EXT_TRIG')
LED_USB_N = Net('LED_USB_N')
LED_CAP_N = Net('LED_CAP_N')

# --- Buses (widths per net_plan.md sections 5-7) ---
ADCA_D = Bus('ADCA_D', 12)
ADCB_D = Bus('ADCB_D', 12)
SRAM_A = Bus('SRAM_A', 18)
SRAM_D = Bus('SRAM_D', 16)
FIFO_D = Bus('FIFO_D', 8)

# ---------------------------------------------------------------------------
# Instantiate blocks (11 calls, 9 blocks — afe_channel and adc_channel x2 each)
# ---------------------------------------------------------------------------

usb_c_input(vbus=VBUS, gnd=GND, usb_dp=USB_DP, usb_dm=USB_DM)

power_digital(vbus=VBUS, gnd=GND, v3v3_d=V3V3_D, v1v2=V1V2)

power_analog(
    vbus=VBUS, gnd=GND, pwren_n=PWREN_N,
    v3v3_a=V3V3_A, v3v3_clk=V3V3_CLK,
    v5_a=V5_A, vn5_a=VN5_A,
    vref_0v5_a=VREF_0V5_A, vref_0v5_b=VREF_0V5_B,
)

clock_gen(
    v3v3_clk=V3V3_CLK, gnd=GND,
    clk_adc_a=CLK_ADC_A, clk_adc_b=CLK_ADC_B, clk_10m=CLK_10M,
)

afe_channel(
    bnc_sig=BNC_A_SIG, gnd=GND, v5_a=V5_A, vn5_a=VN5_A, v3v3_a=V3V3_A,
    vref_0v5=VREF_0V5_A, adc_in=ADC_A_IN, adc_vinn=ADC_A_VINN, ch='A',
)
afe_channel(
    bnc_sig=BNC_B_SIG, gnd=GND, v5_a=V5_A, vn5_a=VN5_A, v3v3_a=V3V3_A,
    vref_0v5=VREF_0V5_B, adc_in=ADC_B_IN, adc_vinn=ADC_B_VINN, ch='B',
)

adc_channel(
    adc_in=ADC_A_IN, adc_vinn=ADC_A_VINN, adc_clk=CLK_ADC_A, pdwn=ADCA_PDWN,
    v3v3_a=V3V3_A, v3v3_d=V3V3_D, gnd=GND, data=ADCA_D, otr=ADCA_OTR, ch='A',
)
adc_channel(
    adc_in=ADC_B_IN, adc_vinn=ADC_B_VINN, adc_clk=CLK_ADC_B, pdwn=ADCB_PDWN,
    v3v3_a=V3V3_A, v3v3_d=V3V3_D, gnd=GND, data=ADCB_D, otr=ADCB_OTR, ch='B',
)

sram_buffer(
    v3v3_d=V3V3_D, gnd=GND, addr=SRAM_A, data=SRAM_D,
    ce_n=SRAM_CE_N, oe_n=SRAM_OE_N, we_n=SRAM_WE_N, ub_n=SRAM_UB_N, lb_n=SRAM_LB_N,
)

usb_bridge(
    vbus=VBUS, v3v3_d=V3V3_D, gnd=GND, usb_dp=USB_DP, usb_dm=USB_DM,
    fifo_data=FIFO_D, rxf_n=FIFO_RXF_N, txe_n=FIFO_TXE_N,
    rd_n=FIFO_RD_N, wr_n=FIFO_WR_N, oe_n=FIFO_OE_N,
    clk60=CLK60, pwren_n=PWREN_N,
)

fpga_core(
    v3v3_d=V3V3_D, v1v2=V1V2, gnd=GND,
    adca_data=ADCA_D, adca_otr=ADCA_OTR, adca_pdwn=ADCA_PDWN,
    adcb_data=ADCB_D, adcb_otr=ADCB_OTR, adcb_pdwn=ADCB_PDWN,
    clk_10m=CLK_10M, clk60=CLK60,
    sram_addr=SRAM_A, sram_data=SRAM_D,
    sram_ce_n=SRAM_CE_N, sram_oe_n=SRAM_OE_N, sram_we_n=SRAM_WE_N,
    sram_ub_n=SRAM_UB_N, sram_lb_n=SRAM_LB_N,
    fifo_data=FIFO_D, rxf_n=FIFO_RXF_N, txe_n=FIFO_TXE_N,
    rd_n=FIFO_RD_N, wr_n=FIFO_WR_N, oe_n=FIFO_OE_N,
    ext_trig=EXT_TRIG, led_usb_n=LED_USB_N, led_cap_n=LED_CAP_N,
)

if __name__ == '__main__':
    # SKiDL 3.0.0's Circuit.ERC() returns None -- error/warning tallies are counted on
    # the (shared) erc_logger.error / .warning CountCalls wrappers as a side effect.
    from skidl.logger import erc_logger
    ERC()
    num_errors = erc_logger.error.count
    num_warnings = erc_logger.warning.count
    # Gate the export: only write outputs if ERC is clean (0 errors).
    if num_errors == 0:
        generate_netlist(file_='outputs/dual_adc_usb.net')
        generate_xml(file_='outputs/dual_adc_usb_bom.xml')
        print(f'\nExport OK: 0 errors, {num_warnings} warnings.')
    else:
        print(f'\nExport SKIPPED: ERC reported {num_errors} errors, {num_warnings} warnings.')
